<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Mc.Common.Services.EmailSender.Abstractions\Mc.Common.Services.EmailSender.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Mc.Common.Services.EmailSender.DependencyInjection\Mc.Common.Services.EmailSender.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\src\Mc.Common.Services.EmailSender\Mc.Common.Services.EmailSender.csproj" />
  </ItemGroup>

</Project>
